repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        files: "\\.(md|markdown|html|js|css|scss|json|yaml|yml)$"
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: "\\.js$"
  - repo: https://github.com/pre-commit/mirrors-stylelint
    rev: v16.8.2
    hooks:
      - id: stylelint
        files: "\\.css$"
        additional_dependencies:
          - stylelint-config-standard@35.0.0
  - repo: local
    hooks:
      - id: htmlhint
        name: htmlhint
        entry: htmlhint
        language: node
        files: "\\.html$"
        additional_dependencies:
          - htmlhint@1.1.4
